apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: rhel-coreos-10-2-on-pull-request
  namespace: coreos-tenant
  labels:
    appstudio.openshift.io/application: rhel-coreos-10-2
    appstudio.openshift.io/component: rhel-coreos-10-2
    pipelines.appstudio.openshift.io/type: build
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/coreos/rhel-coreos-config?rev={{revision}}
    build.appstudio.redhat.com/cancel-in-progress: "true"
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "pull_request" && target_branch == "main" && (
        ".tekton/rhel-coreos-10-2-on-pull-request.yaml".pathChanged() ||
        "fedora-coreos-config/**".pathChanged() ||
        "live/**".pathChanged() ||
        "overlay.d/**".pathChanged() ||
        "tests/kola/**".pathChanged() ||
        "build-args-rhel-10.2.conf".pathChanged() ||
        "common.yaml".pathChanged() ||
        "group".pathChanged() ||
        "image-default.yaml".pathChanged() ||
        "image-rhel-10.2.yaml".pathChanged() ||
        "kola-denylist.yaml".pathChanged() ||
        "manifest-el10-shared.yaml".pathChanged() ||
        "manifest-rhel-10.2.yaml".pathChanged() ||
        "packages-overrides.yaml".pathChanged() ||
        "packages-rhcos.yaml".pathChanged() ||
        "passwd".pathChanged()
      )
  creationTimestamp: null
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/coreos-tenant/rhel-coreos-10-2:on-pr-{{revision}}
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args-file
    value: build-args-rhel-10.2.conf
  - name: workingdir-mount
    value: /run/src
  - name: build-platforms
    value:
    - linux/amd64
    #- linux/arm64
    #- linux/ppc64le
    #- linux/s390x
  - name: clone-depth
    value: 50
  - name: hermetic
    value: true
  - name: prefetch-input
    value: '[{"type": "rpm", "path": "."}]'
  - name: image-expires-after
    value: 5d
  - name: additional-secret
    value: container-image-build
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog-pr:buildah-build-bootc-multi-platform-oci-ta-be8cacbbe7bc1936819e25f033fef0c266013256-7431dbaf7463
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-rhel-coreos-10-2
